language: cpp
#dist: trusty

before_install:
    - eval "${MATRIX_EVAL}"

install:
  # Install conan
  - pip install --user -q conan
  # Automatic detection of your arch, compiler, etc.
  # - conan user

script:
  - cd hello
  - mkdir build && cd build
  - conan install .. --build -s compiler.libcxx=libstdc++11
  - cmake ..
  - cmake --build .
  - ./bin/test_hello

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
              #            - python-3.6
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
