build: false

platform: x64

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user # Create the conan data directory

build_script:
  - mkdir build && cd build
  - conan install .. --build
  - cmake .. -G "%CMAKE_GENERATOR%"
  - cmake --build . --config Release

test_script:
  - cd bin && test_hello.exe

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64
